### ISSUE TITLE
Automatically bring up a docker stack, on a docker swarm

### ISSUE THREAD

**Issue by haydockjp** [markcallen/docker-swarm-aws-terraform#1]
Hi Mark,

Could you point me towards any documentation / suggestions on how to start up a stack on a docker swarm automatically? At the meetup I didn't have access to AWS and over the last couple of days I have been playing with the example.

I have changed the packer output AMI to be CentOS and I can bring up my docker swarm, with a docker stack compose file on the master node. What seems to happen is that the master node comes up and the stack is deployed. Then the worker nodes come up, and everything just sits on the master not, leaving the worker nodes looking a little lonely.

This is what I tried

```
provisioner "file" {
source = "${var.stack_compose_file}"
destination = "/tmp/${var.compose_stack}.yml"
}

provisioner "remote-exec" {
inline = [
"if [ ${count.index} -eq 0 ]; then sudo docker swarm init; else sudo docker swarm join ${aws_instance.swarm-manager.0.private_ip}:2377 --token $(docker -H ${aws_instance.swarm-manager.0.private_ip} swarm join-token -q manager); fi"
]
}

provisioner "remote-exec" {
inline = [
"if [ ${count.index} -eq 0 ]; then sudo docker stack deploy --compose-file /tmp/${var.compose_stack}.yml ${var.compose_stack}; fi"
]
}
```

Any help would be greatly appreciated!
Thanks in advance.
Jon

**Comment by markcallen** [comment]
I would recommend putting the code to startup the stack in the remote-exec of the 
````
resource "null_resource" "cluster"
`````
which you'll find in the swarm/swarm.tf file.

This will be executed whenever a node is added to the swarm.

You'll need to upload the compose file to the node in use in when you run:
````
docker stack ....
````

**Comment by haydockjp** [comment]
Thanks. For some reason I had made the assumption that you should only bring the stack up on one of the manager nodes.

**Comment by markcallen** [comment]
Nope, the:
````
docker -H ${element(aws_instance.swarm-manager.*.private_ip, 0)}:2375 ...
````
Run the command on the first manager node in the swarm, even from one the nodes.
